### ISSUE TITLE
composer install problem

### ISSUE THREAD

**Issue by saifalink** [fathur/Arisan#10]
ada problem pada install composer 
![eror composer](https://user-images.githubusercontent.com/17897618/42018406-3326f132-7adc-11e8-8f04-398456296fd5.png)
ini hanya terjadi sewaktu install composer di folder arisan.
sedangakan instal composer di folder source code lain bisa. mohon pencerahannya

**Comment by fathur** [comment]
Hai @saifalink Terima kasih atas laporan issuenya, ternyata phpoffce/phpexcel berubah nama menjadi phpoffice/phpspreadsheet. Dan tidak dapat menggunakan mcrypt di versi PHP 7.1 keatas.

Saya sudah mengupload versi 1.1.2, silahkan dicoba kembali. Dan harap pastikan versi phpnya dibawah 7.1.

Jika ada masalah lagi silahkan komen

**Comment by saifalink** [comment]
saya sudah berhasil dari tahap ke tahap tapi pas buka http://localhost/arisan/public/ muncul seperti dibawah ini
![eror login](https://user-images.githubusercontent.com/17897618/42069570-c04c839c-7b7c-11e8-8847-c8b4f392abd7.png)

**Comment by fathur** [comment]
give the detailed error, with turn on debugging mode
